name: Example workflow using Snyk with continue on error
on: push
jobs:
  security:
    runs-on: node:latest
    steps:
      - uses: actions/checkout@master
      - name: Install package
        run: npm install
    
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
