name: Example workflow using Snyk with continue on error
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Snyk authenticaion
        run: snyk auth
      - uses: snyk/actions/node@master
      - name: Snyk monitor
        run: |
          npm install
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
